### ISSUE TITLE
Allow returning probabilities of individual sentences in perplexity computations

### ISSUE THREAD

**Issue by vgherard** [vgherard/kgrams#28]

**Comment by andreanini** [comment]
Thank you for opening this issue, @vgherard. It would indeed be a useful addition.

Perplexities of sentences can be easily retrieved by doing sapply(input, perplexity, model), where the input is already tokenised as sentences, of course. The problem with this method is that it does not return the perplexity around the sentence boundaries, which, at least for some applications I am interested in, is quite important.

**Comment by vgherard** [comment]
Thanks @andreanini !

`sapply(input, perplexity, model)` looks like a reasonable way to compute perplexities of individual sentences. It would return the log-likelihood of a sentence normalized by its word count... which I'd say it makes sense, if the goal is to compare the perplexity of different sentences (of different lengths).

I don't know whether there exist standard methods to "decompose" additively the perplexity of a corpus into perplexities of individual sentences (or tokens), there might be some subtlety related to normalization... I need to review the literature.

Concerning the issue that you mention: the language models with "Begin-Of-Sentence" and "End-Of-Sentence" tokens that I think you have in mind treat sentences in a document as if they were statistically independent, that's an important limitation to keep into mind.

If you want to model also connections between different (from the grammatical pov) sentences, you should rather treat punctuation as a regular token (maybe transforming all punctuation characters into a special `<DOT>` token). Whether this is useful or not depends on the concrete application. Happy to discuss this in a separate place :)

**Comment by andreanini** [comment]
I understand. Thanks!
